version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=your-secret-key
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: project
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
